package com.example.hemanthlam.connectfour;

import android.widget.Spinner;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Created by hemanthlam on 2/15/18.
 */

public class AutoGeneratedBoardTest {

    @Test
    public void checkSampleWinner() throws Exception {
        int testWins;
        int expected = 0;
        AutoGeneratedBoard testBoard = new AutoGeneratedBoard();
        testWins = testBoard.p1Wins;
        assertEquals(expected, testWins);
        testWins = testBoard.p2Wins;
        assertEquals(expected, testWins);
    }
}
